import Head from "next/head";
import React from "react";
import Navigation from "../_Common/Navigation/Navigation";
import styles from "./layout.module.scss";
import Footer from "../_Common/Footer/Footer";
const Dashboard = ({ children }) => {
  return (
    <>
      <Head>
        <title>Xaad || Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <Navigation />
        <div className={styles.container}>{children}</div>
        <Footer />
      </div>
    </>
  );
};

export default Dashboard;
