import Head from "next/head";
import Home from "../components/Home/Home";
import Signin from "../components/SignIn/signIn";
export default function App() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Signin />
    </>
  );
}
